name: Run E2E and API Tests

on:
  push:
    branches:
      - main

jobs:
  partA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Newman Tests
        run: |
          cd Part_A && npm ci && npm test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Newman_Report
          path: Part_A/reports/report.html
